### ISSUE TITLE
Sandforms not available

### ISSUE THREAD

**Issue by juliafelder** [sandforms/sandforms#62]
Hello, I have problems with accessing an existing sandforms grain, which I created via my fairapps account. The Sandform has been filled out by many people and we urgently need the results. Also some who tried to fill in the form could not access it. It seems very random when the grain can be accessed and when not.

Today it always shows: "ui-56e9e0df64e5074a486f6db8ea5c0220.fair.sandcats.io hat keine Daten gesendet."
I would really appreciate help for accessing the data entered into the form. I can find some text in the backup, but no answers to checkboxes and some text data is also missing.

Also other sandforms seem not available. I am not a developer so I don't know which details to post here to make the problem understandable. Maybe this helps, what I found in the backup 'mongo.log':

Sat Jan  2 10:00:26.600 [initandlisten] MongoDB starting : pid=7 port=4002 dbpath=/var 64-bit host=sandbox
Sat Jan  2 10:00:26.604 [initandlisten] db version v2.4.9
Sat Jan  2 10:00:26.607 [initandlisten] git version: 29a7a6bac226e01df929347a7feafdc6f3d57a2c
Sat Jan  2 10:00:26.607 [initandlisten] build info: Linux zero 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 BOOST_LIB_VERSION=1_49
Sat Jan  2 10:00:26.607 [initandlisten] allocator: tcmalloc
Sat Jan  2 10:00:26.607 [initandlisten] options: { bind_ip: "127.0.0.1", dbpath: "/var", fork: true, logpath: "/var/mongo.log", noauth: true, nohttpinterface: true, noprealloc: true, port: 4002 }
************** 
old lock file: /var/mongod.lock.  probably means unclean shutdown,
but there are no journal files to recover.
this is likely human error or filesystem corruption.
please make sure that your journal directory is mounted.
found 2 dbs.
see: http://dochub.mongodb.org/core/repair for more information
*************
Sat Jan  2 10:00:26.611 [initandlisten] exception in initAndListen: 12596 old lock file, terminating
Sat Jan  2 10:00:26.612 dbexit: 
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: going to close listening sockets...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: going to flush diaglog...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: going to close sockets...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: waiting for fs preallocator...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: lock for final commit...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: final commit...
Sat Jan  2 10:00:26.612 [initandlisten] shutdown: closing all files...
Sat Jan  2 10:00:26.612 [initandlisten] closeAllFiles() finished
Sat Jan  2 10:00:26.612 dbexit: really exiting now

**Comment by paulproteus** [comment]
Hi @juliafelder,

I'm not a Sandforms developer, but I have some experience by which I can share some advice.

Each Sandforms grain has its own database, and it sounds like there is a problem with this one's database.

The best next step is to get a copy of the Sandforms app package use the MongoDB repair commands listed here: https://docs.mongodb.com/manual/tutorial/recover-data-following-unexpected-shutdown/

When you run it, it will probably look something like

```
/path/to/sandforms-app/bin/mongod --repair /path/to/grain-backup
```

where `/path/to/sandforms-app/` is the location of the unpacked Sandforms app, and `/path/to/grain-backup` is the path to the unzipped grain backup.

I'm hopeful that this can be useful to you, and/or that you can work together with the FairApps folks to work through this.

Best,

Asheesh.

**Comment by ocdtrekkie** [comment]
@paulproteus advice was what I was going to suggest. If you aren't an admin on the server, you can also download a backup of the grain, fix it, and then repackage the backup and restore it to the server, though it will restore as a copy, not over the original grain.

**Comment by juliafelder** [comment]
thanks a lot for your advice @paulproteus  and @ocdtrekkie. I will try your suggestions soon. I also found this log, does this also indicate a broken database? I just wonder, because even if I create a new random sandform grain I get the the same problem, that I cannot open it

throw(ex);
						      ^
Error: failed to connect to [127.0.0.1:4002]
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
sandstorm/sandstorm-http-bridge.c++:2250: warning: App isn't listening for TCP connections after 30 seconds. Continuing to attempt to connect; address->toString() = 127.0.0.1:8000
** HTTP-BRIDGE: App server exited with status code: 8
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: privileged
** Starting mongo...
** Starting Meteor...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
all output going to: /var/mongo.log
log file [/var/mongo.log] exists; copied to temporary file [/var/mongo.log.2021-01-03T07-32-09]
ERROR: child process failed, exited with error number 100

/programs/server/node_modules/fibers/future.js:278

**Comment by juliafelder** [comment]
I got lost in trying out the instructions now :) yes I think I will try with the FairApps people, because I guess the conditions might be a bit special if I use Sandform via Fairapps.
 Thanks a lot to both of you
